const path = [
    { x: 0, y: 50 },
    { x: 100, y: 50 },
    { x: 100, y: 200 },
    { x: 300, y: 200 },
    { x: 300, y: 400 },
    { x: 600, y: 400 },
    { x: 600, y: 550 },
    { x: 800, y: 550 }
];

const levels = [
    {
        enemies: [
            { health: 50, speed: 1 },
            { health: 50, speed: 1 },
            { health: 50, speed: 1 },
            { health: 50, speed: 1 },
            { health: 50, speed: 1 },
            { health: 50, speed: 1 },
            { health: 50, speed: 1 },
            { health: 50, speed: 1 },
            { health: 50, speed: 1 },
            { health: 50, speed: 1 }
        ],
        startingCoins: 100,
        towerCost: 50,
        rewardPerKill: 10
    },
    {
        enemies: [
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 },
            { health: 60, speed: 1.2 }
        ],
        startingCoins: 120,
        towerCost: 50,
        rewardPerKill: 15
    },
    {
        enemies: [
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 },
            { health: 70, speed: 1.4 }
        ],
        startingCoins: 140,
        towerCost: 50,
        rewardPerKill: 20
    },
    {
        enemies: [
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 },
            { health: 80, speed: 1.6 }
        ],
        startingCoins: 160,
        towerCost: 50,
        rewardPerKill: 25
    },
    {
        enemies: [
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 },
            { health: 90, speed: 1.8 }
        ],
        startingCoins: 180,
        towerCost: 50,
        rewardPerKill: 30
    }
];
